# Generated by Django 3.1.7 on 2021-07-24 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=30)),
                ('crimeType', models.CharField(choices=[('Robbery', 'Robbery'), ('Theft', 'Theft'), ('Violent', 'Violent'), ('Fraud', 'Fraud'), ('Cyber crime', 'Cyber crime')], default='Select Crime', max_length=15)),
                ('case_desc', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Studied', 'Studied'), ('Finished', 'Finished')], default='Pending', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dist_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prov_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RIBStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.province')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sect_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vil_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspectNID', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('date_arrested', models.DateTimeField(auto_now_add=True, null=True)),
                ('relation', models.CharField(max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.case')),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.cell')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.district')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.province')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.village')),
            ],
        ),
        migrations.CreateModel(
            name='StationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officerNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('Captain', 'Captain'), ('Major', 'Major'), ('General', 'General'), ('Major General', 'Major General')], max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=5)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.ribstation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RIBHeadquarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.province')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OfficerNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('officerimage', models.ImageField(blank=True, max_length=154, null=True, upload_to='images/')),
                ('rank', models.CharField(choices=[('Captain', 'Captain'), ('Major', 'Major'), ('General', 'General'), ('Major General', 'Major General')], max_length=30)),
                ('recruit_year', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidenceCategory', models.CharField(choices=[('Physical', 'Physical'), ('Logical', 'Logical')], default='Select Category', max_length=15)),
                ('evidence_note', models.CharField(max_length=255)),
                ('points', models.CharField(max_length=10)),
                ('officerimage', models.ImageField(blank=True, max_length=154, null=True, upload_to='images/')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.suspect')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.officer'),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('adminimage', models.ImageField(blank=True, max_length=154, null=True, upload_to='images/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
