# Generated by Django 3.1.7 on 2021-09-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporterNID', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('relation', models.CharField(max_length=30)),
                ('vote', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.suspect')),
            ],
        ),
    ]
