# Generated by Django 3.1.7 on 2021-10-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0002_reporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspect',
            name='case',
        ),
        migrations.AddField(
            model_name='case',
            name='suspects',
            field=models.ManyToManyField(blank=True, null=True, to='crime.Suspect'),
        ),
        migrations.CreateModel(
            name='ViolentQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspectNID', models.CharField(max_length=16)),
                ('q1', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q2', models.CharField(choices=[('I was there at crime scene', 'I was there at crime scene'), ('I were at work', 'I were at work'), ('I was Near the crime scene', 'I was Near the crime scene'), ('I was Too Far in different district', 'I was Too Far in different district')], max_length=50)),
                ('q6', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q3', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q4', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q5', models.CharField(max_length=10)),
                ('date_arrested', models.DateTimeField(auto_now_add=True, null=True)),
                ('vote', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q7', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q8', models.DateField()),
                ('q9', models.CharField(blank=True, max_length=100)),
                ('q10', models.CharField(blank=True, max_length=100)),
                ('q11', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q12', models.CharField(max_length=10)),
                ('q13', models.CharField(choices=[('I was there', 'I was there'), ("I don't know", "I don't know"), ('I know the Victim', 'I know the Victim'), ("I've met with the Victim", "I've met with the Victim")], max_length=100)),
                ('q14', models.CharField(blank=True, max_length=100)),
                ('q15', models.CharField(blank=True, max_length=300)),
                ('q16', models.CharField(blank=True, max_length=1)),
                ('note', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.case')),
            ],
        ),
        migrations.CreateModel(
            name='RobberyQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspectNID', models.CharField(max_length=16)),
                ('q1', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q2', models.CharField(choices=[('I was there at crime scene', 'I was there at crime scene'), ('I were at work', 'I were at work'), ('I was Near the crime scene', 'I was Near the crime scene'), ('I was Too Far in different district', 'I was Too Far in different district')], max_length=50)),
                ('q6', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q3', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q4', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q5', models.CharField(max_length=10)),
                ('date_arrested', models.DateTimeField(auto_now_add=True, null=True)),
                ('vote', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q7', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q8', models.DateField()),
                ('q9', models.CharField(blank=True, max_length=100)),
                ('q10', models.CharField(blank=True, max_length=100)),
                ('q11', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q12', models.CharField(max_length=10)),
                ('q13', models.CharField(choices=[('I was there', 'I was there'), ("I don't know", "I don't know"), ('I know the Victim', 'I know the Victim'), ("I've met with the Victim", "I've met with the Victim")], max_length=100)),
                ('q14', models.CharField(blank=True, max_length=100)),
                ('q15', models.CharField(blank=True, max_length=300)),
                ('q16', models.CharField(blank=True, max_length=1)),
                ('note', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.case')),
            ],
        ),
        migrations.CreateModel(
            name='MurderQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspectNID', models.CharField(max_length=16)),
                ('q1', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q2', models.CharField(choices=[('I was there at crime scene', 'I was there at crime scene'), ('I were at work', 'I were at work'), ('I was Near the crime scene', 'I was Near the crime scene'), ('I was Too Far in different district', 'I was Too Far in different district')], max_length=50)),
                ('q6', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q3', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q4', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q5', models.CharField(max_length=10)),
                ('date_arrested', models.DateTimeField(auto_now_add=True, null=True)),
                ('vote', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q7', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q8', models.DateField()),
                ('q9', models.CharField(blank=True, max_length=100)),
                ('q10', models.CharField(blank=True, max_length=100)),
                ('q11', models.CharField(choices=[('Yes', 'YES'), ('No', 'NO')], max_length=3)),
                ('q12', models.CharField(max_length=10)),
                ('q13', models.CharField(choices=[('I was there', 'I was there'), ("I don't know", "I don't know"), ('I know the Victim', 'I know the Victim'), ("I've met with the Victim", "I've met with the Victim")], max_length=100)),
                ('q14', models.CharField(blank=True, max_length=100)),
                ('q15', models.CharField(blank=True, max_length=300)),
                ('q16', models.CharField(blank=True, max_length=1)),
                ('note', models.CharField(max_length=150)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.case')),
            ],
        ),
    ]
