# Generated by Django 3.1.7 on 2021-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0004_auto_20211010_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='cell',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='village',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
