# Generated by Django 3.1.7 on 2021-10-10 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0006_auto_20211010_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='murderquestions',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.suspect'),
        ),
        migrations.AddField(
            model_name='robberyquestions',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.suspect'),
        ),
        migrations.AddField(
            model_name='violentquestions',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.suspect'),
        ),
    ]
