# Generated by Django 3.1.7 on 2021-10-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0007_auto_20211010_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_address',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_name',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='case',
            name='crimeType',
            field=models.CharField(choices=[('Robbery', 'Robbery'), ('Violent', 'Violent'), ('Murder', 'Murder')], default='Select Crime', max_length=15),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Studied', 'Studied'), ('Finished', 'Finished')], max_length=15),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='note',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
