# Generated by Django 3.1.7 on 2021-10-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0008_auto_20211011_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporter',
            name='suspect',
        ),
        migrations.AddField(
            model_name='suspect',
            name='witnes',
            field=models.ManyToManyField(blank=True, null=True, to='crime.Reporter'),
        ),
    ]
