# Generated by Django 3.1.7 on 2021-10-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0009_auto_20211011_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspect',
            old_name='witnes',
            new_name='reporters',
        ),
    ]
