# Generated by Django 3.1.7 on 2021-10-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0014_suspect_officer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationUser',
        ),
    ]
