# Generated by Django 3.1.7 on 2021-10-17 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crime', '0015_delete_stationuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('officerNationalId', models.CharField(max_length=16)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('rank', models.CharField(choices=[('Captain', 'Captain'), ('Major', 'Major'), ('General', 'General'), ('Major General', 'Major General')], max_length=30)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=5)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crime.ribstation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
