# Generated by Django 3.1.7 on 2021-10-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0016_stationuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationuser',
            name='officerNationalId',
        ),
        migrations.RemoveField(
            model_name='stationuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='stationuser',
            name='station',
        ),
        migrations.RemoveField(
            model_name='stationuser',
            name='username',
        ),
        migrations.AddField(
            model_name='stationuser',
            name='nationalId',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='stationuser',
            name='officerimage',
            field=models.ImageField(blank=True, max_length=154, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='stationuser',
            name='recruit_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationuser',
            name='ribstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.ribstation'),
        ),
        migrations.AlterField(
            model_name='stationuser',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stationuser',
            name='f_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stationuser',
            name='l_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='stationuser',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stationuser',
            name='rank',
            field=models.CharField(choices=[('Captain', 'Captain'), ('Major', 'Major'), ('General', 'General'), ('Major General', 'Major General')], max_length=30, null=True),
        ),
    ]
