# Generated by Django 3.1.7 on 2022-01-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0019_answer_caqs_crime_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='murderquestions',
            old_name='suspectNID',
            new_name='reporterNID',
        ),
        migrations.RenameField(
            model_name='robberyquestions',
            old_name='suspectNID',
            new_name='reporterNID',
        ),
        migrations.RenameField(
            model_name='violentquestions',
            old_name='suspectNID',
            new_name='reporterNID',
        ),
    ]
