# Generated by Django 3.1.7 on 2022-01-30 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0020_auto_20220106_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caqs',
            name='crime',
        ),
    ]
