# Generated by Django 3.1.7 on 2022-01-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0021_remove_caqs_crime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAQW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.answer')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.question')),
                ('witness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.reporter')),
            ],
        ),
    ]
