# Generated by Django 3.1.7 on 2022-01-31 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0023_questionreporter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robberyquestions',
            name='case',
        ),
        migrations.RemoveField(
            model_name='robberyquestions',
            name='suspect',
        ),
        migrations.RemoveField(
            model_name='violentquestions',
            name='case',
        ),
        migrations.RemoveField(
            model_name='violentquestions',
            name='suspect',
        ),
        migrations.DeleteModel(
            name='MurderQuestions',
        ),
        migrations.DeleteModel(
            name='RobberyQuestions',
        ),
        migrations.DeleteModel(
            name='ViolentQuestions',
        ),
    ]
