# Generated by Django 3.1.7 on 2022-01-31 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0024_auto_20220131_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='QuestionSuspect',
        ),
        migrations.AlterField(
            model_name='caqw',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.questionreporter'),
        ),
    ]
