# Generated by Django 3.1.7 on 2022-02-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0025_auto_20220131_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionreporter',
            name='questionId',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='questionsuspect',
            name='questionId',
            field=models.TextField(blank=True, max_length=4, null=True),
        ),
    ]
