# Generated by Django 3.1.7 on 2022-02-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0026_auto_20220202_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_note',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='questionreporter',
            name='questionId',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='questionsuspect',
            name='questionId',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='note',
            field=models.TextField(max_length=150),
        ),
    ]
