# Generated by Django 3.1.7 on 2022-02-14 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0027_auto_20220202_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.DeleteModel(
            name='Village',
        ),
        migrations.AlterField(
            model_name='questionreporter',
            name='questionId',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='questionsuspect',
            name='questionId',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reporter',
            name='reporterNID',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='suspectNID',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
