# Generated by Django 3.1.7 on 2022-02-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0028_auto_20220214_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporter',
            name='reporterNID',
            field=models.CharField(max_length=16),
        ),
    ]
