# Generated by Django 3.1.7 on 2022-02-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0030_auto_20220214_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='crimeType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.crime'),
        ),
    ]
