# Generated by Django 3.1.7 on 2022-02-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0031_auto_20220214_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='victim_age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
