# Generated by Django 3.1.7 on 2022-02-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0032_case_victim_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='crimeType',
            field=models.CharField(choices=[('Robbery', 'Robbery'), ('Violent', 'Violent'), ('Murder', 'Murder')], max_length=30, null=True),
        ),
    ]
