# Generated by Django 3.1.7 on 2022-03-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0033_auto_20220214_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspectCriminalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspectNID', models.CharField(max_length=16, unique=True)),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('date_arrested', models.DateTimeField(auto_now_add=True, null=True)),
                ('relation', models.CharField(max_length=30)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('mother_name', models.CharField(blank=True, max_length=100)),
                ('province', models.CharField(blank=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(max_length=150)),
                ('evidences', models.ManyToManyField(blank=True, null=True, to='crime.Evidence')),
                ('reporters', models.ManyToManyField(blank=True, null=True, to='crime.Reporter')),
                ('ribstation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.ribstation')),
                ('stationuser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crime.stationuser')),
            ],
        ),
    ]
