# Generated by Django 3.1.7 on 2022-03-01 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crime', '0034_suspectcriminalrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='officerimage',
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidencerimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
